
directory: /home/jlivin25/Music/Library/flacimports
library: /home/jlivin25/.config/beets/flac/musiclibrary.blb

import:
    copy: no
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: folder

plugins: embedart chroma fetchart convert permissions

pluginpath: /home/jlivin25/.config/beets/myplugins

threaded: yes

color: yes

match:
    strong_rec_thresh: 0.55

paths:
    default: $albumartist/$album/$track - $title - $artist
    singleton: Singletons/$track - $title - $artist
    comp: Various/$album/$track - $title - $artist
    albumtype:soundtrack: Soundtracks/$album/$track - $title - $artist

permissions:
    file: 777
    dir: 777
